name: Manual workflow
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Maven Verify
        run: mvn -B clean verify
